name: Deploy to Firebase (produção)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependências do projeto
        run: |
          cd functions
          npm install

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy completo para Firebase (Hosting + Functions)
        run: |
          firebase deploy
